---
- name: "Build a container with ansible"
  hosts: localhost
  connection: local
  tasks:
    - name: stop current running container
      command: docker stop mina
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm mina
      ignore_errors: yes

    - name: remove comingsoon-image
      command: docker rmi minabottros001/minaweb
      ignore_errors: yes

    - name: build image 
      command: docker build -t minabottros001/minaweb .

    - name: run container
      command: docker run -d --name mina -p 8084:80 minaweb